config/routes.rb
Rails.application.routes.draw do
  root "rooms#index"
  resources :messages
  resources :rooms
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  has_one_attached :image

  validate :acceptable_image

  private

  def acceptable_image
    return unless image.attached?

    if image.byte_size > 2.megabytes
      errors.add(:image, "is too big. Maximum size is 2MB.")
    end

    acceptable_types = ["image/jpeg", "image/png", "image/jpg"]
    unless acceptable_types.include?(image.content_type)
      errors.add(:image, "must be a JPEG or PNG.")
    end
  end

end

app/models/room.rb
class Room < ApplicationRecord

  attr_accessor :topic_name

  belongs_to :user
  belongs_to :topic

  has_many :messages, dependent: :destroy
  has_many :participants, through: :messages, source: :user

  validates :name, presence: true, uniqueness: true, format: { with: /\A[A-Z]/}
  validates :topic_name, presence: true, format: { with: /\A[A-Z]/}
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :rooms, dependent: :destroy
  validates :name, presence: true, format: { with: /\A[A-Z]/}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :participated_rooms, through: :messages, source: :room

  def username
    email.split("@").first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	# def new
	# 	@message = Message.new
	# end

	def create

		@message = Message.new(message_params)
		@message.user = current_user
		@message.save

		SendMessageJob.perform_later(@message.id)
	end
		
	private

	def message_params
		params.require(:message).permit(:body, :room_id, :image)
	end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :set_room, only: [:show]
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @topics = Topic.last(10)

    @messages = Message.order(created_at: :desc).last(5)

    if params[:q].present?
      topic = Topic.find_by_name(params[:q])
      @rooms = topic ? topic.rooms : Room.where('name ILIKE :q OR "desc" ILIKE :q', q: "%#{params[:q]}%")
    else
      @rooms = Room.order(created_at: :desc)
    end
  end

  def new
    @room = current_user.rooms.new()
  end

  def create
    @room = current_user.rooms.create(room_params)

    if params[:room][:topic_name].present?
      @topic = Topic.find_or_create_by(name: params[:room][:topic_name])
      @room.topic_id = @topic.id
    end

    if @room.save
      redirect_to @room, notice: 'Room was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:name, :desc, :topic_name)
  end

  def message_params
    params.require(:message).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def formatted_timestamp(time)
    time.in_time_zone("Asia/Kolkata").strftime("%d %B %Y, %I:%M %p")
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "StudyMate" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>


    <%= render "rooms/navbar" %>

    <div class="container mt-5">
      <%= yield %>
    </div>

  </body>
  
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true, html: { multipart: true }) do |form| %>
  

  <%= form.text_field :body, placeholder: "Type your message here..." %>

  <%= form.file_field :image, id: "message_image" %>

  <%= form.submit "Send", id: "send_button", disabled: true %>

  <%= form.hidden_field :room_id, value: room.id %>

<% end %>

app/views/messages/_message.html.erb
<%= message.user.username %>: <%= message.body %><br>

<% if message.image.attached? %>
  <p>
    <%= image_tag url_for(message.image), width: "250" %>
  </p>
<% end %>

<small><%= formatted_timestamp(message.created_at) %></small>

<br><br>

app/views/rooms/_activity.html.erb
<h5>Recent activity</h5>
<% if @messages.any? %>
  <div id="recent_activity_list">
    <% @messages.each do |message| %>
      <%= render partial: "rooms/recent_activity", locals: { message: message } %>
    <% end %>
  </div>
<% else %>
  <p class="text-danger mt-3">No recent activity!</p>
<% end %>

app/views/rooms/_form.html.erb
<% unless @room.errors.empty? %>
  
  <h4><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h4>
  <ul>
  
    <% @room.errors.full_messages.each do |message| %>
  
      <li><%= message %></li>
  
    <% end %>
  
  </ul>

<% end %>


<%= form_with model: @room do |form| %>
  
  <div>
  
    <%= form.label "Room name" %>
  
    <%= form.text_field :name %>
  
  </div>

  
  <div>
  
    <%= form.label "Room topic" %>
  
    <%= form.text_field :topic_name %>
  
  </div>


  <div>
  
    <%= form.label "Room description" %>
  
    <%= form.text_area :desc %>
  
  </div>

  <%= form.submit %>

<% end %>

app/views/rooms/_navbar.html.erb
<nav class="navbar bg-light shadow-sm py-2">
  <div class="container">
    <div class="row w-100 align-items-center">

      <div class="col-sm-4">
        <%= link_to "StudyMate", root_url, class: "navbar-brand" %>
      </div>

      <div class="col-sm-4">

        <%= form_with url: rooms_path, method: :get, local: true, html: { class: "w-100" } do %>
          <%= text_field_tag :q, params[:q], placeholder: "Search rooms", class: "form-control" %>
        <% end %>
      </div>

      <div class="col-sm-4 text-end">
        <% if user_signed_in? %>
          <div class="dropdown">
            <button class="btn btn-link text-decoration-none text-dark dropdown-toggle" type="button" id="userDropdown" data-bs-toggle="dropdown" aria-expanded="false">
              @<%= current_user.username %>
            </button>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
              <li><a class="dropdown-item" href="#">Dashboard</a></li>
              <li><%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item text-danger" %></li>
            </ul>
          </div>
        <% else %>
          <%= button_to "Sign in", new_user_session_path, class: "btn btn-outline-success" %>
        <% end %>
      </div>

    </div>
  </div>
</nav>

<style>
@media (max-width: 578px) {
  .navbar .row {
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
  }

  .navbar .col-sm-4 {
    width: 100%;
    margin-bottom: 1rem; /* Adds space between brand, search, and button */
  }

  .navbar .form-control {
    margin: 0 auto;
  }

  .navbar .dropdown {
    margin: 0 auto;
  }

  .navbar .dropdown-menu {
    left: 50% !important;
    transform: translateX(-50%) !important;
    right: auto !important;
    text-align: center;
  }

  .navbar .dropdown-toggle {
    width: 100%;
  }

  .navbar .btn {
    width: 100%;
  }
}


</style>

app/views/rooms/_participants.html.erb
<div id="participants">

<%= pluralize(room.participants.uniq.count, "participant") %>

<ul>
	<li><%= "#{room.user.username} - host" %></li>
	<% unless room.participants.empty? %>
		<% (room.participants.uniq - [room.user]).each do |participant| %>

			<li><%= participant.username %></li>

		<% end %>
	<% end %>

</ul>

</div>

app/views/rooms/_recent_activity.html.erb
<div id="recent_activity_message_<%= message.id %>" class="toast show mb-3 shadow-none border" role="alert" aria-live="assertive" aria-atomic="true">
  <div class="toast-header border-0 mb-0">
    <strong class="me-auto">
      <%= link_to "@#{message.user.username}", "#", class: "text-decoration-none" %>
    </strong>
    <small class="text-muted"><%= time_ago_in_words(message.created_at) %> ago</small>
  </div>
  <div class="toast-body pt-0">
    <span class="fw-semibold">replied:</span> <%= message.body %>
    <br>
    <span class="text-muted">in </span>
    <%= link_to message.room.name, room_path(message.room), class: "fw-bold text-decoration-none" %>
  </div>
</div>




<style>
  @media (max-width: 578px) {
    .toast {
      width: 100%;
    }
  }
</style>

app/views/rooms/_rooms.html.erb
<% unless @rooms.empty? %>
  <% @rooms.each do |room| %>
    <div class="jumbotron jumbotron-fluid bg-light rounded mt-3">
      <div class="container p-3">
        <div class="row mb-3">
          <div class="col">
            <small class="text-secondary">
            Created by <%= link_to "@#{room.user.username}", "#", class: "text-decoration-none text-secondary" %>
          </small>
          </div>
          <div class="col text-end">
            <p class="card-text"><small class="text-body-secondary"><%= time_ago_in_words(room.created_at) %> ago</small></p>
          </div>
        </div>

        <h3 class="display-6">
          <%= link_to room.name, room_path(room), class: "text-dark text-decoration-none" %>
        </h3>
        <p class="lead">
          <%= truncate(room.desc, length: 70) %>
        </p>

        <hr class="my-3">

        <div class="row">
          <div class="col">
            <small class="text-secondary">
              <%= pluralize(room.participants.uniq.count, 'participant') %>
            </small>
          </div>
          <div class="col text-end">
            <span class="badge rounded-pill text-bg-secondary">
              <%= room.topic.name %>
            </span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <p class="text-danger mt-3">No rooms found!</p>
<% end %>

app/views/rooms/_topic.html.erb
<h5>Browse by topics</h5>

<ul class="list-group">
  <% unless @topics.empty? %>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <%= link_to "All", root_url, class: "text-decoration-none text-dark" %>
      <span class="badge text-bg-secondary rounded-pill"><%= Room.count %></span>
    </li>
    <% @topics.each do |topic| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <%= link_to topic.name, "#{root_url}rooms?q=#{topic.name}", class: "text-decoration-none text-dark" %>
        <span class="badge text-bg-secondary rounded-pill"><%= topic.rooms.count %></span>
      </li>
    <% end %>
  <% else %>
    <p class="text-danger mt-3">No topics found!</p>
  <% end %>
</ul>

app/views/rooms/index.html.erb
<%= content_for(:title, "StudyMate - All rooms") %>


<div class="row">
  
  <div class="col-sm-3 mb-5">
    <%= render "topic" %>
  </div>
  
  <div class="col-sm-6 mb-5">
    <div class="row">
      <div class="col">
        <h5>All rooms</h5>
        <small><%= pluralize(@rooms.count, 'room') %> available</small>
      </div>
      <div class="col text-end">
        <%= link_to "New room", new_room_url, class: "btn btn-outline-secondary" %>
      </div>
    </div>

    <%= render "rooms" %>
  </div>
  
  <div class="col-sm-3">
    <%= render "activity" %>
  </div>

</div>

app/views/rooms/new.html.erb
<%= content_for(:title, "Create new room")  %>
  
<h3>New room</h3>

<%= render "form" %>	

<%= link_to "back", root_url %>

app/views/rooms/show.html.erb
<%= content_for(:title, "Room - #{@room.name}")  %>

<div id="room-id" data-room-id="<%= @room.id %>"></div>

<div style="display: flex;">

	<div style="width: 80%;">

		<%= link_to "back", root_url %>

		<h3><%= @room.name %> chat</h3>

		<div style="min-height: 70vh;", id="messages">

			<% unless @room.messages.empty? %>

				<% @room.messages.each do |message| %>

					<p><%= render "messages/message", message: message %></p>

				<% end %>

			<% end %>

		</div>

		<%= render "messages/form", message: Message.new, room: @room %>

	</div>


	<div style="width: 20%;">
		<%= render "participants", room: @room %>
	</div>

</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>